name: ✨ Feature Request
description: Suggest a new feature for the TimeDancers Meditation app
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out this form to help us understand your idea.

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area would this feature affect?
      options:
        - Meditation Experience
        - Timer System
        - Chakra Orbs
        - Audio/Chimes
        - Settings
        - Onboarding
        - UI/Design
        - Accessibility
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Essential for my use case
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Describe the problem or limitation...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How would you use this feature? Provide a specific example.
      placeholder: Describe how you would use this feature...
    validations:
      required: true

  - type: textarea
    id: meditation_context
    attributes:
      label: Meditation Context
      description: How does this feature relate to meditation practice or the TimeDancers philosophy?
      placeholder: Explain the meditation/spiritual context...

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity (if known)
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - UI change or small addition
        - Medium - New component or moderate logic
        - Complex - Major system change or new architecture
        - Unknown - I'm not sure

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples that would help explain this feature.

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: This feature aligns with the TimeDancers meditation philosophy
          required: true
        - label: I have provided sufficient detail for the development team to understand the request
          required: true
